export enum AnalysisErrorCode {
  INVALID_URL = "INVALID_URL",

  SCRAPE_FAILED = "SCRAPE_FAILED",

  SCRAPE_TEMPORARILY_UNAVAILABLE = "SCRAPE_TEMPORARILY_UNAVAILABLE",

  INSUFFICIENT_CONTENT = "INSUFFICIENT_CONTENT",

  UNSUPPORTED_WEBSITE = "UNSUPPORTED_WEBSITE",

  AI_GENERATION_FAILED = "AI_GENERATION_FAILED",

  AI_SCHEMA_VALIDATION_FAILED = "AI_SCHEMA_VALIDATION_FAILED",

  RESEARCH_FAILED = "RESEARCH_FAILED",

  INTERNAL_ERROR = "INTERNAL_ERROR",

  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  
  AI_RATE_LIMITED = "AI_RATE_LIMITED",
}
