import dotenv from "dotenv";

dotenv.config();

export const env = {
  GEMINI_API_KEY: process.env.GEMINI_API_KEY!,
  FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY!,
  TAVILY_API_KEY: process.env.TAVILY_API_KEY!,
  GOOGLE_CLOUD_PROJECT: process.env.GOOGLE_CLOUD_PROJECT!,
  GOOGLE_CLOUD_LOCATION: process.env.GOOGLE_CLOUD_LOCATION!,
  AGENT_PLATFORM_API_KEY: process.env.AGENT_PLATFORM_API_KEY!,
  GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS!,
};
